# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(398, 106)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 398, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTime = QtWidgets.QMenu(self.menubar)
        self.menuTime.setObjectName("menuTime")
        self.menuSpace = QtWidgets.QMenu(self.menubar)
        self.menuSpace.setObjectName("menuSpace")
        self.menuMoran_s_I = QtWidgets.QMenu(self.menuSpace)
        self.menuMoran_s_I.setObjectName("menuMoran_s_I")
        self.menuTime_Space = QtWidgets.QMenu(self.menubar)
        self.menuTime_Space.setObjectName("menuTime_Space")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionTable = QtWidgets.QAction(MainWindow)
        self.actionTable.setObjectName("actionTable")
        self.actionTrend_Graph = QtWidgets.QAction(MainWindow)
        self.actionTrend_Graph.setObjectName("actionTrend_Graph")
        self.actionGlobal = QtWidgets.QAction(MainWindow)
        self.actionGlobal.setObjectName("actionGlobal")
        self.actionLocal = QtWidgets.QAction(MainWindow)
        self.actionLocal.setObjectName("actionLocal")
        self.actionStatic_Map = QtWidgets.QAction(MainWindow)
        self.actionStatic_Map.setObjectName("actionStatic_Map")
        self.actionDynamic_Map = QtWidgets.QAction(MainWindow)
        self.actionDynamic_Map.setObjectName("actionDynamic_Map")
        self.actionSTACF = QtWidgets.QAction(MainWindow)
        self.actionSTACF.setObjectName("actionSTACF")
        self.actionSTPACF = QtWidgets.QAction(MainWindow)
        self.actionSTPACF.setObjectName("actionSTPACF")
        self.actionSTARMA = QtWidgets.QAction(MainWindow)
        self.actionSTARMA.setObjectName("actionSTARMA")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionTable)
        self.menuTime.addAction(self.actionTrend_Graph)
        self.menuMoran_s_I.addAction(self.actionGlobal)
        self.menuMoran_s_I.addAction(self.actionLocal)
        self.menuSpace.addAction(self.menuMoran_s_I.menuAction())
        self.menuTime_Space.addAction(self.actionDynamic_Map)
        self.menuTime_Space.addAction(self.actionSTACF)
        self.menuTime_Space.addAction(self.actionSTPACF)
        self.menuTime_Space.addAction(self.actionSTARMA)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTime.menuAction())
        self.menubar.addAction(self.menuSpace.menuAction())
        self.menubar.addAction(self.menuTime_Space.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuTime.setTitle(_translate("MainWindow", "Time"))
        self.menuSpace.setTitle(_translate("MainWindow", "Space"))
        self.menuMoran_s_I.setTitle(_translate("MainWindow", "Moran\'s I"))
        self.menuTime_Space.setTitle(_translate("MainWindow", "Time-Space"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionTable.setText(_translate("MainWindow", "Table"))
        self.actionTrend_Graph.setText(_translate("MainWindow", "Trend Graph"))
        self.actionGlobal.setText(_translate("MainWindow", "Global"))
        self.actionLocal.setText(_translate("MainWindow", "Local"))
        self.actionStatic_Map.setText(_translate("MainWindow", "Static Map"))
        self.actionDynamic_Map.setText(_translate("MainWindow", "Dynamic Map"))
        self.actionSTACF.setText(_translate("MainWindow", "STACF"))
        self.actionSTPACF.setText(_translate("MainWindow", "STPACF"))
        self.actionSTARMA.setText(_translate("MainWindow", "STARMA"))

